// <auto-generated />
using System;
using Imperatle.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imperatle.Api.Migrations
{
    [DbContext(typeof(ImperatleDbContext))]
    [Migration("20261006212623_AddPlayerProgressDateIndex")]
    partial class AddPlayerProgressDateIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Imperatle.Api.Models.DailyChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmpireId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.HasIndex("EmpireId");

                    b.ToTable("DailyChallenges");
                });

            modelBuilder.Entity("Imperatle.Api.Models.Empire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaPrecision")
                        .HasColumnType("integer");

                    b.Property<string>("CapitalEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CapitalPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Continents")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("DurationNotesEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DurationNotesPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndYear")
                        .HasColumnType("integer");

                    b.Property<int>("EndYearPrecision")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguagePt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MapBorderConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeakAreaKm2")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryContinent")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceYear")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceYearPrecision")
                        .HasColumnType("integer");

                    b.Property<string>("ReligionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReligionPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.Property<int>("StartYearPrecision")
                        .HasColumnType("integer");

                    b.Property<string>("SubEraEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubEraPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Empires");
                });

            modelBuilder.Entity("Imperatle.Api.Models.EmpireHint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpireId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpireId");

                    b.ToTable("EmpireHints");
                });

            modelBuilder.Entity("Imperatle.Api.Models.PlayerChallengeProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptsUsed")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Correct")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmpireId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmpireId");

                    b.HasIndex("AnonymousId", "Date")
                        .IsUnique();

                    b.ToTable("PlayerChallengeProgress");
                });

            modelBuilder.Entity("Imperatle.Api.Models.DailyChallenge", b =>
                {
                    b.HasOne("Imperatle.Api.Models.Empire", "Empire")
                        .WithMany()
                        .HasForeignKey("EmpireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empire");
                });

            modelBuilder.Entity("Imperatle.Api.Models.EmpireHint", b =>
                {
                    b.HasOne("Imperatle.Api.Models.Empire", "Empire")
                        .WithMany("Hints")
                        .HasForeignKey("EmpireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empire");
                });

            modelBuilder.Entity("Imperatle.Api.Models.PlayerChallengeProgress", b =>
                {
                    b.HasOne("Imperatle.Api.Models.Empire", "Empire")
                        .WithMany()
                        .HasForeignKey("EmpireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empire");
                });

            modelBuilder.Entity("Imperatle.Api.Models.Empire", b =>
                {
                    b.Navigation("Hints");
                });
#pragma warning restore 612, 618
        }
    }
}
