// <auto-generated />
using Imperatle.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imperatle.Api.Migrations
{
    [DbContext(typeof(ImperatleDbContext))]
    [Migration("20260825211505_ExpandEmpireDomain")]
    partial class ExpandEmpireDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Imperatle.Api.Models.Empire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferenceYear")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearPrecision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Empires");
                });

            modelBuilder.Entity("Imperatle.Api.Models.EmpireHint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpireId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpireId");

                    b.ToTable("EmpireHints");
                });

            modelBuilder.Entity("Imperatle.Api.Models.EmpireHint", b =>
                {
                    b.HasOne("Imperatle.Api.Models.Empire", "Empire")
                        .WithMany("Hints")
                        .HasForeignKey("EmpireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empire");
                });

            modelBuilder.Entity("Imperatle.Api.Models.Empire", b =>
                {
                    b.Navigation("Hints");
                });
#pragma warning restore 612, 618
        }
    }
}
